# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RILab Cloud Services
email: hello@rilab.io
description: Save your business software cost with the touch of a button.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://rilab.io" # the base hostname & protocol for your site

# Logo settings
logo-image-url:
font-awesome-icon-logo: RILab Cloud Services

# Social settings
github_username: 
twitter_username: 
facebook_URL:
instagram_username:

# Build settings
markdown: kramdown
